### ISSUE TITLE
Cannot compile on macOS 13.2.1 with XCode 14.2

### ISSUE THREAD

**Issue by jms1voalte** [waywardgeek/infnoise#97]
Compiling from commit `8edb00bb` on macOS 13.2.1 with XCode 14.2 fails with the following message:

```
infnoise.c:63:60: error: parameter 'entropy' set but not used [-Werror,-Wunused-but-set-parameter]
bool outputBytes(uint8_t *bytes, uint32_t length, uint32_t entropy, bool writeDevRandom, const char **message) {
                                                           ^
1 error generated.
make: *** [Makefile.macos:28: infnoise.o] Error 1
```

I see line 92 says `entropy = 0; // suppress warning`, but this looks like it's just trading one warning for another.

I was able to make it compile by adding `-Wno-unused-but-set-parameter` to the `CFLAGS` value in `Makefile.macos`, and the resulting executable does seem to work (i.e. `sudo ./infnoise | dd status=none bs=256 count=1 | hexdump -C` produces different random-looking output every time). However, I'm not sure if this is the best way to handle things.

**Comment by kg4zow** [comment]
I just tried to compile it again, on a different machine - this time macOS 26.4, on a machine with just the XCode command line tools installed. **Different error message**, but again I was able to work around it by disabling that particular warning.

**Error message**

```
infnoise.c:67:95: error: unused parameter 'forceKernelReseed' [-Werror,-Wunused-parameter]
   67 | bool outputBytes(uint8_t *bytes, uint32_t length, uint32_t entropy, bool writeDevRandom, bool forceKernelReseed, uint32_t feedFrequency, const char **message) {
      |                                                                                               ^
1 error generated.
```

**Work around**

```
(master|u=) (jms1@beast) 198 ~/git/waywardgeek/infnoise/software $ git diff -w
diff --git a/software/Makefile.macos b/software/Makefile.macos
index 646743e..09336ef 100644
--- a/software/Makefile.macos
+++ b/software/Makefile.macos
@@ -25,7 +25,7 @@ infnoise: libinfnoise.a infnoise.o daemon.o
        $(CC) $(CFLAGS) -o infnoise infnoise.o daemon.o libinfnoise.a $(FTDI) -lm -L. -L $(FTDILOCL)

 %.o: %.c infnoise.h libinfnoise.h
-       $(CC) -c -o $@ $< $(CFLAGS)
+       $(CC) -c -o $@ $< $(CFLAGS) -Wno-unused-parameter

 KeccakF-1600-reference.o: Keccak/KeccakF-1600-reference.c Keccak/KeccakF-1600-interface.h Keccak/brg_endian.h
        $(CC) -c -o $@ $< $(CFLAGS)
(master *%|u=) (jms1@beast) 199 ~/git/waywardgeek/infnoise/software $
```

**Other info that might be useful**

```
(master|u=) (jms1@beast) 182 ~/git/waywardgeek/infnoise/software $ git remote -v
origin	https://github.com/waywardgeek/infnoise (fetch)
origin	https://github.com/waywardgeek/infnoise (push)
(master|u=) (jms1@beast) 183 ~/git/waywardgeek/infnoise/software $ git fetch -p
(master|u=) (jms1@beast) 184 ~/git/waywardgeek/infnoise/software $ git pull
Already up to date.
(master|u=) (jms1@beast) 185 ~/git/waywardgeek/infnoise/software $ git rev-parse HEAD
878d50cc1a7ffecb329beee2cb992fc3255fb3a0
(master|u=) (jms1@beast) 186 ~/git/waywardgeek/infnoise/software $ cc --version
Apple clang version 21.0.0 (clang-2100.0.123.102)
Target: arm64-apple-darwin25.4.0
Thread model: posix
InstalledDir: /Library/Developer/CommandLineTools/usr/bin
```

Also, if it isn't obvious, I am the same human as @jms1voalte. That Github user was used for a job that I've since been laid off from.
